### ISSUE TITLE
Scholarly Communication

### ISSUE THREAD

**Issue by zuguang0425** [shedding-ash/shedding-ash#1]
Hello! Can I have your address and contact details to discuss this with you?

**Comment by shedding-ash** [comment]
Welcome
You can add my QQ 1400752438




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shedding-ash/shedding-ash"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月27日(星期五) 下午3:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[shedding-ash/shedding-ash] Scholarly Communication (Issue #1)





 
Hello! Can I have your address and contact details to discuss this with you?
